// <auto-generated />
using System;
using Fortigate_Gui.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fortigate_Gui.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210302135443_CustomUserData")]
    partial class CustomUserData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Fortigate")
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fortigate_Gui.Areas.Identity.Data.CustomUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<string>("FactoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ConfigFile", b =>
                {
                    b.Property<int>("ConfigfileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FilterID")
                        .HasColumnType("int");

                    b.Property<int?>("Ip4PolicyID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VPNtunnelID")
                        .HasColumnType("int");

                    b.HasKey("ConfigfileID");

                    b.HasIndex("ClientID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("FilterID");

                    b.HasIndex("Ip4PolicyID");

                    b.HasIndex("VPNtunnelID");

                    b.ToTable("ConfigFile");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Customer", b =>
                {
                    b.Property<int>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConfigfileID")
                        .HasColumnType("int");

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerID");

                    b.HasIndex("ConfigfileID");

                    b.HasIndex("UserID")
                        .IsUnique()
                        .HasFilter("[UserID] IS NOT NULL");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeID");

                    b.HasIndex("ClientID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.EnumAcces", b =>
                {
                    b.Property<int>("EnumAccesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnumAccesID");

                    b.ToTable("EnumAcces");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.EnumAlias", b =>
                {
                    b.Property<int>("EnumAliasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnumAliasID");

                    b.ToTable("EnumAlias");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.EnumMode", b =>
                {
                    b.Property<int>("EnumModeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnumModeID");

                    b.ToTable("EnumMode");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Filter", b =>
                {
                    b.Property<int>("FilterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConfigFilter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FilterID");

                    b.ToTable("Filter");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Interface", b =>
                {
                    b.Property<int>("InterfaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EnumAccesID")
                        .HasColumnType("int");

                    b.Property<int>("EnumAliasID")
                        .HasColumnType("int");

                    b.Property<string>("EnumModeID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EnumModeID1")
                        .HasColumnType("int");

                    b.Property<string>("Ip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SecondaryIp")
                        .HasColumnType("bit");

                    b.Property<string>("Subnet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vdom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneInterfaceID")
                        .HasColumnType("int");

                    b.HasKey("InterfaceID");

                    b.HasIndex("EnumAccesID");

                    b.HasIndex("EnumAliasID");

                    b.HasIndex("EnumModeID1");

                    b.HasIndex("ZoneInterfaceID");

                    b.ToTable("Interface");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Ip4Policy", b =>
                {
                    b.Property<int>("Ip4PolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConfigfileID")
                        .HasColumnType("int");

                    b.Property<string>("DestinationAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DestinationInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ip4PolicyID");

                    b.HasIndex("ConfigfileID");

                    b.ToTable("Ip4Policy");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Setting", b =>
                {
                    b.Property<int>("SettingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DefaultPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ServerCert")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceAddressV6")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceInterface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StringSourceAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TunnelIpPool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TunnelIpv6Pool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VPNtunnelID")
                        .HasColumnType("int");

                    b.HasKey("SettingID");

                    b.HasIndex("VPNtunnelID");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.VPNtunnel", b =>
                {
                    b.Property<int>("VPNtunnelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ConfigfileID")
                        .HasColumnType("int");

                    b.Property<string>("IpPool")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SettingID")
                        .HasColumnType("int");

                    b.Property<bool>("SplitTunneling")
                        .HasColumnType("bit");

                    b.Property<bool>("TunnelMode")
                        .HasColumnType("bit");

                    b.HasKey("VPNtunnelID");

                    b.HasIndex("ConfigfileID");

                    b.HasIndex("SettingID");

                    b.ToTable("VPNtunnel");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ZoneInterfaceID")
                        .HasColumnType("int");

                    b.HasKey("ZoneID");

                    b.HasIndex("ZoneInterfaceID");

                    b.ToTable("Zone");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ZoneInterface", b =>
                {
                    b.Property<int>("ZoneInterfaceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("InterfaceID")
                        .HasColumnType("int");

                    b.Property<int?>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("ZoneInterfaceID");

                    b.HasIndex("InterfaceID");

                    b.HasIndex("ZoneID");

                    b.ToTable("ZoneInterface");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ZonePolicy", b =>
                {
                    b.Property<int>("ZonePolicyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ip4PolicyID")
                        .HasColumnType("int");

                    b.Property<int>("ZoneID")
                        .HasColumnType("int");

                    b.HasKey("ZonePolicyID");

                    b.HasIndex("Ip4PolicyID");

                    b.HasIndex("ZoneID");

                    b.ToTable("ZonePolicy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Client", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ConfigFile", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Models.Customer", null)
                        .WithMany("Configfiles")
                        .HasForeignKey("CustomerID");

                    b.HasOne("Fortigate_Gui.Models.Filter", "Filter")
                        .WithMany()
                        .HasForeignKey("FilterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Models.Ip4Policy", "Ip4Policy")
                        .WithMany()
                        .HasForeignKey("Ip4PolicyID");

                    b.HasOne("Fortigate_Gui.Models.VPNtunnel", "VPNtunnel")
                        .WithMany()
                        .HasForeignKey("VPNtunnelID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Customer", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.ConfigFile", "Configfile")
                        .WithMany()
                        .HasForeignKey("ConfigfileID");

                    b.HasOne("Fortigate_Gui.Areas.Identity.Data.CustomUser", "CustomUser")
                        .WithOne("Customer")
                        .HasForeignKey("Fortigate_Gui.Models.Customer", "UserID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Employee", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.Client", null)
                        .WithMany("Employees")
                        .HasForeignKey("ClientID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Interface", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.EnumAcces", "EnumAcces")
                        .WithMany()
                        .HasForeignKey("EnumAccesID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Models.EnumAlias", "EnumAlias")
                        .WithMany()
                        .HasForeignKey("EnumAliasID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Models.EnumMode", "EnumMode")
                        .WithMany()
                        .HasForeignKey("EnumModeID1");

                    b.HasOne("Fortigate_Gui.Models.ZoneInterface", null)
                        .WithMany("Interfaces")
                        .HasForeignKey("ZoneInterfaceID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Ip4Policy", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.ConfigFile", null)
                        .WithMany("Ip4Policies")
                        .HasForeignKey("ConfigfileID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Setting", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.VPNtunnel", null)
                        .WithMany("Settings")
                        .HasForeignKey("VPNtunnelID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.VPNtunnel", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.ConfigFile", null)
                        .WithMany("VPNtunnels")
                        .HasForeignKey("ConfigfileID");

                    b.HasOne("Fortigate_Gui.Models.Setting", "Setting")
                        .WithMany()
                        .HasForeignKey("SettingID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.Zone", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.ZoneInterface", null)
                        .WithMany("Zones")
                        .HasForeignKey("ZoneInterfaceID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ZoneInterface", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.Interface", "Interface")
                        .WithMany()
                        .HasForeignKey("InterfaceID");

                    b.HasOne("Fortigate_Gui.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneID");
                });

            modelBuilder.Entity("Fortigate_Gui.Models.ZonePolicy", b =>
                {
                    b.HasOne("Fortigate_Gui.Models.Ip4Policy", "Ip4Policy")
                        .WithMany()
                        .HasForeignKey("Ip4PolicyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Models.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Fortigate_Gui.Areas.Identity.Data.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Fortigate_Gui.Areas.Identity.Data.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortigate_Gui.Areas.Identity.Data.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Fortigate_Gui.Areas.Identity.Data.CustomUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
